project:
  type: website

website:
  title: "Execution Engine Admin Guide"
  navbar:
    background: primary
    search: true
  sidebar:
    contents:
      - section: "About"
        contents:
          - href: index.qmd
            text: "Introduction"
      - text: "---"
      - section: "Installation"
        contents:
          - href: install-linux.qmd
            text: "Install on Linux"
          - href: install-windows.qmd
            text: "Install on Windows"
          - href: install-mac.qmd
            text: "Install on Mac"
      - text: "---"
      - section: "Contributing"
        contents:
          - href: architecture.qmd

format:
  html:
    theme:
      light: [flatly, custom-style-light.scss]
      dark: [darkly, custom-style-dark.scss]
    scss: custom-style.scss
    toc: false

editor: visual

