---
title: "Darwin ~ OHDSI Execution Engine"
---

The Darwin Execution Engine is a web application that runs Darwin / OHDSI studies written in R code in pre-configured runtime environments using Docker.

-   Easy installation

-   Preconfigured environments out of the box

-   Easily extendable with your own studies or environments

-   Free and Open Source Software (Apache Licensed)

-   Actively used and supported by Darwin EU

This guide describes everything you need to know to install, use, and contribute to the Darwin Execution Engine.

## Why use Execution Engine?

The Observational Health Data Science and Informatics (OHDSI) community is the largest federated network of standardized observational health data ever created. Using the OMOP Common Data Model and standardize vocabularies as a foundation, researchers can work across institutions to conduct network research. Darwin EU is pioneering this approach for regulatory use in the European Union.

Even though the data and analytics are standardized, the execution environments where the analytic code runs are not. The word "*environment*" is somewhat overloaded in computer science so it is helpful to clearly define it. For the purpose of this website "*runtime environment*", or simply "*environment*" for short refers to the operating system, R/python versions, other system dependencies and R package dependencies that the analytic code uses to run. Execution Engine aims to standardize the runtime environment for OHDSI network studies and gives researchers confidence that their code will run successfully across a network of data nodes.

## 
