# Build and push the execution UI and API containers to the container repo
on:
  push:
    branches: main

name: Build_and_push_dev_UI_and_API_container_images

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout source code repo'
          uses: actions/checkout@main

        - name: 'Build and push UI image'
          uses: azure/docker-login@v1
          with:
            username: github-actions
            password: ${{ secrets.acr_token }}
            login-server: executionengine.azurecr.io

        - run: |
            cd ${{ github.workspace }}/execution-engine-ui
            docker build -t executionengine.azurecr.io/execution-engine-ui:latest .
            docker login -u github-actions -p ${{ secrets.acr_token }} executionengine.azurecr.io
            docker push executionengine.azurecr.io/execution-engine-ui:latest

        - name: 'Build and push API image'
          uses: azure/docker-login@v1
          with:
            username: github-actions
            password: ${{ secrets.acr_token }}
            login-server: executionengine.azurecr.io
        - run: |
            cd ${{ github.workspace }}/execution-engine-api
            docker build -t executionengine.azurecr.io/execution-engine-api:latest .
            docker login -u github-actions -p ${{ secrets.acr_token }} executionengine.azurecr.io
            docker push executionengine.azurecr.io/execution-engine-api:latest

