# Build and push the execution UI and API containers to the container repo
on:
  push:
    branches: main

name: Build_and_push_dev_UI_and_API_container_images

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout source code repo'
          uses: actions/checkout@main

        # - name: 'Login via Azure CLI'
        #   uses: azure/login@v1
        #   with:
        #     creds: ${{ secrets.acr_token }}

        - name: 'Build and push UI image'
          uses: azure/docker-login@v1
          with:
            username: github-actions
            password: ${{ secrets.acr_token }}
            login-server: executionengine.azurecr.io

        - run: |
            docker build -t executionengine.azurecr.io/execution-engine-ui:dev execution-engine-ui/Dockerfile
            docker login -u github-actions -p ${{ secrets.acr_token }} executionengine.azurecr.io
            docker push executionengine.azurecr.io/execution-engine-ui:dev

        - name: 'Build and push API image'
          uses: azure/docker-login@v1
          with:
            username: github-actions
            password: ${{ secrets.acr_token }}
            login-server: executionengine.azurecr.io
        - run: |
            docker build -t executionengine.azurecr.io/execution-engine-api:dev execution-engine-api/Dockerfile
            docker login -u github-actions -p ${{ secrets.acr_token }} executionengine.azurecr.io
            docker push executionengine.azurecr.io/execution-engine-api:dev

#  - name: 'Deploy to Azure Container Instances'
#   uses: 'azure/aci-deploy@v1'
#   with:
#     resource-group: ${{ secrets.RESOURCE_GROUP }}
#     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
#     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#     registry-username: ${{ secrets.REGISTRY_USERNAME }}
#     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#     name: aci-sampleapp
#     location: 'west us'
